using System.Text.Json;
using HireSkilledHelpers.Workers;
using Microsoft.Xna.Framework;

Point start = new(0, 1);
Point goal = new(4, 1);

WorkerRouteTileKind Corridor(Point point, WorkerRouteTileKind middle)
{
    if (point.X < 0 || point.X > 4 || point.Y != 1)
        return WorkerRouteTileKind.Impassable;
    return point.X == 2 ? middle : WorkerRouteTileKind.Open;
}

WorkerObstacleRoutePlanner small = new(start, new[] { goal }, point => Corridor(point, WorkerRouteTileKind.SmallDebris));
WorkerObstaclePlanStatus status = Run(small, out WorkerObstacleClearance? clearance);
Assert(status == WorkerObstaclePlanStatus.ClearSmallDebris && clearance == new WorkerObstacleClearance(new Point(2, 1), new Point(1, 1)),
    "Only the small blocker on a useful route should be selected, from its reachable neighbor.");

HashSet<Point> rejectedDebris = new() { new Point(2, 1) };
WorkerObstacleRoutePlanner retry = new(start, new[] { goal }, point => rejectedDebris.Contains(point)
    ? WorkerRouteTileKind.Impassable : Corridor(point, WorkerRouteTileKind.SmallDebris));
status = Run(retry, out clearance);
Assert(status == WorkerObstaclePlanStatus.NoRoute && clearance is null,
    "A failed work-debris approach must be excluded from the next search instead of selected forever.");

Point secondGoal = new(4, 3);
WorkerRouteTileKind TwoCorridors(Point point) =>
    point.X < 0 || point.X > 4 || point.Y < 1 || point.Y > 3
        || point.Y == 2 && point.X != 0 ? WorkerRouteTileKind.Impassable
        : point.X == 2 ? WorkerRouteTileKind.SmallDebris : WorkerRouteTileKind.Open;
Point branchStart = new(0, 2);
WorkerObstacleRoutePlanner firstBranch = new(branchStart, new[] { goal, secondGoal }, TwoCorridors);
status = Run(firstBranch, out clearance);
Assert(status == WorkerObstaclePlanStatus.ClearSmallDebris && clearance is not null,
    "A blocked work route should identify one useful small obstacle.");
Point failedTile = clearance!.ObstacleTile;
WorkerObstacleRoutePlanner alternateBranch = new(branchStart, new[] { goal, secondGoal },
    point => point == failedTile ? WorkerRouteTileKind.Impassable : TwoCorridors(point));
status = Run(alternateBranch, out clearance);
Assert(status == WorkerObstaclePlanStatus.ClearSmallDebris && clearance is not null
    && clearance.ObstacleTile != failedTile,
    "After one debris approach fails, work planning should choose another eligible corridor.");

WorkerObstacleRoutePlanner large = new(start, new[] { goal }, point => Corridor(point, WorkerRouteTileKind.LargeObstacle));
status = Run(large, out clearance);
Assert(status == WorkerObstaclePlanStatus.BlockedByLargeObstacle && clearance is null,
    "An unavoidable large obstacle must be reported without selecting it for clearing.");

WorkerObstacleRoutePlanner mixed = new(start, new[] { goal }, point => point.X == 1 && point.Y == 1
    ? WorkerRouteTileKind.SmallDebris : Corridor(point, WorkerRouteTileKind.LargeObstacle));
status = Run(mixed, out clearance);
Assert(status == WorkerObstaclePlanStatus.BlockedByLargeObstacle && clearance is null,
    "A small obstacle should remain untouched if clearing it cannot reach the job past a large obstacle.");

WorkerObstacleRoutePlanner hard = new(start, new[] { goal }, point => Corridor(point, WorkerRouteTileKind.Impassable));
status = Run(hard, out clearance);
Assert(status == WorkerObstaclePlanStatus.NoRoute && clearance is null,
    "Map walls and protected player objects must not be described as large removable obstacles.");

WorkerObstacleRoutePlanner detour = new(start, new[] { goal }, point =>
    point.X < 0 || point.X > 4 || point.Y < 1 || point.Y > 2
        ? WorkerRouteTileKind.Impassable
        : point == new Point(2, 1) ? WorkerRouteTileKind.SmallDebris : WorkerRouteTileKind.Open);
status = Run(detour, out clearance);
Assert(status == WorkerObstaclePlanStatus.ReachableClearRoute && clearance is null,
    "A free detour should not cause unnecessary clearing.");

WorkerObstacleRoutePlanner openExit = new(start, new[] { goal }, _ => WorkerRouteTileKind.Open);
status = Run(openExit, out clearance);
Assert(status == WorkerObstaclePlanStatus.ReachableClearRoute && clearance is null,
    "An existing clear route must be distinguished from a truly unreachable exit.");
Assert(!WorkerReturnFallbackPolicy.MayUseEmergencyWarp(true, false, true)
    && !WorkerReturnFallbackPolicy.MayUseEmergencyWarp(false, true, true)
    && !WorkerReturnFallbackPolicy.MayUseEmergencyWarp(false, false, false)
    && WorkerReturnFallbackPolicy.MayUseEmergencyWarp(false, false, true),
    "Emergency placement requires no visible route, no clearable debris route, and a safe landing.");

object existing = new();
object produced = new();
object laterPlayerDrop = new();
HashSet<object> before = new() { existing };
HashSet<object> captured = WorkerDebrisCapture.CaptureNew(before, new[] { existing, produced });
Assert(captured.SetEquals(new[] { produced }), "Capture must include only debris generated by the tool action.");
Assert(WorkerDebrisCapture.BelongsToZone(produced, before, captured, near: false)
    && !WorkerDebrisCapture.BelongsToZone(existing, before, captured, near: true)
    && !WorkerDebrisCapture.BelongsToZone(laterPlayerDrop, before, captured, near: true),
    "Exact capture must preserve older and later player drops on the ground.");

WorkerObstacleReport report = new() { Id = "current", Message = "Big logs blocked my path.", Task = WorkerTaskKind.ChopHardwood, LocationName = "Farm" };
WorkerObstacleReport? reloaded = JsonSerializer.Deserialize<WorkerObstacleReport>(JsonSerializer.Serialize(report));
Assert(reloaded?.Message == report.Message && WorkerObstacleReportPolicy.MatchesAcknowledgment(reloaded, "current"),
    "The report must survive save serialization and acknowledge its matching ID.");
Assert(!WorkerObstacleReportPolicy.MatchesAcknowledgment(reloaded, "stale")
    && !WorkerObstacleReportPolicy.MatchesAcknowledgment(null, "current"),
    "A delayed multiplayer acknowledgment must not erase a newer or missing report.");

int stoneActionLimit = WorkerObstacleToolProgressPolicy.GetMaximumActions(initialDurability: 7, damagePerToolAction: 1, hardLimit: 32);
Assert(stoneActionLimit == 7, "Small stone work must be bounded by the actual remaining durability instead of a four-swing cutoff.");
Assert(WorkerObstacleToolProgressPolicy.Evaluate(true, true, 7, 0, 1, stoneActionLimit) == WorkerObstacleToolActionStatus.Completed
    && WorkerObstacleToolProgressPolicy.Evaluate(false, false, 7, 7, 1, stoneActionLimit) == WorkerObstacleToolActionStatus.Completed,
    "A completed tool action or removed object must finish clearing immediately.");
Assert(WorkerObstacleToolProgressPolicy.Evaluate(false, true, 7, 6, 1, stoneActionLimit) == WorkerObstacleToolActionStatus.Continue
    && WorkerObstacleToolProgressPolicy.Evaluate(false, true, 7, 7, 1, stoneActionLimit) == WorkerObstacleToolActionStatus.NoProgress
    && WorkerObstacleToolProgressPolicy.Evaluate(false, true, 1, 0, stoneActionLimit, stoneActionLimit) == WorkerObstacleToolActionStatus.ActionLimitReached,
    "Durability progress must continue, while stalled or exhausted work stops safely.");
Assert(WorkerObstacleToolProgressPolicy.GetMaximumActions(1000, 1, 32) == 32,
    "Malformed or unusually durable small litter must still have a finite safety bound.");

Assert((int)WorkerTaskKind.ClearDebris == 7
    && (int)WorkerTaskKind.ChopHardwood == 6,
    "The new saved assignment must not change existing task IDs.");
Assert(WorkerTaskPolicy.IsTaskAllowed(WorkerProfession.Farmer, WorkerTaskKind.ClearDebris)
    && WorkerTaskPolicy.IsTaskAllowed(WorkerProfession.Forager, WorkerTaskKind.ClearDebris)
    && WorkerTaskPolicy.GetTasks(WorkerProfession.Farmer).Contains(WorkerTaskKind.ClearDebris)
    && WorkerTaskPolicy.GetTasks(WorkerProfession.Forager).Contains(WorkerTaskKind.ClearDebris),
    "Both professions must offer and accept the assigned debris job.");
Assert(!WorkerTaskPolicy.IsTaskAllowed(WorkerProfession.Farmer, WorkerTaskKind.ChopHardwood)
    && !WorkerTaskPolicy.IsTaskAllowed(WorkerProfession.Forager, WorkerTaskKind.WaterCrops),
    "Adding the shared job must preserve profession-specific restrictions.");

Console.WriteLine("Obstacle route checks passed: small clearing, failed-approach recovery, large reporting, exact drops, acknowledgment, and shared debris assignment.");

static WorkerObstaclePlanStatus Run(WorkerObstacleRoutePlanner planner, out WorkerObstacleClearance? clearance)
{
    WorkerObstaclePlanStatus status;
    int updates = 0;
    do
    {
        status = planner.Advance(2, 64, out clearance);
        Assert(++updates <= 100, "A bounded obstacle search must finish in a small test grid.");
    } while (status == WorkerObstaclePlanStatus.Searching);
    return status;
}

static void Assert(bool condition, string message)
{
    if (!condition)
        throw new Exception(message);
}

// Quarry ruby durability is five; the steel mining tool should complete in two
// successful impacts without reaching the no-progress/action-limit safeguards.
int miningBudget = WorkerObstacleToolProgressPolicy.GetMaximumActions(5, WorkerMiningPolicy.PickaxeDamage, 32);
Assert(miningBudget == 2, "Steel mining pickaxe must use its actual damage in the bounded action budget.");
Assert(WorkerObstacleToolProgressPolicy.Evaluate(false, true, 5, 2, 1, miningBudget)
    == WorkerObstacleToolActionStatus.Continue, "First mining impact must allow another hit on a durable node.");
Assert(WorkerObstacleToolProgressPolicy.Evaluate(true, true, 2, -1, 2, miningBudget)
    == WorkerObstacleToolActionStatus.Completed, "Final mining impact must complete exactly once.");
