using System.Text.Json;
using FarmingCapitalist.Workers;
using Microsoft.Xna.Framework;

Point start = new(0, 1);
Point goal = new(4, 1);

WorkerRouteTileKind Corridor(Point point, WorkerRouteTileKind middle)
{
    if (point.X < 0 || point.X > 4 || point.Y != 1)
        return WorkerRouteTileKind.Impassable;
    return point.X == 2 ? middle : WorkerRouteTileKind.Open;
}

WorkerObstacleRoutePlanner small = new(start, new[] { goal }, point => Corridor(point, WorkerRouteTileKind.SmallDebris));
WorkerObstaclePlanStatus status = Run(small, out WorkerObstacleClearance? clearance);
Assert(status == WorkerObstaclePlanStatus.ClearSmallDebris && clearance == new WorkerObstacleClearance(new Point(2, 1), new Point(1, 1)),
    "Only the small blocker on a useful route should be selected, from its reachable neighbor.");

WorkerObstacleRoutePlanner large = new(start, new[] { goal }, point => Corridor(point, WorkerRouteTileKind.LargeObstacle));
status = Run(large, out clearance);
Assert(status == WorkerObstaclePlanStatus.BlockedByLargeObstacle && clearance is null,
    "An unavoidable large obstacle must be reported without selecting it for clearing.");

WorkerObstacleRoutePlanner mixed = new(start, new[] { goal }, point => point.X == 1 && point.Y == 1
    ? WorkerRouteTileKind.SmallDebris : Corridor(point, WorkerRouteTileKind.LargeObstacle));
status = Run(mixed, out clearance);
Assert(status == WorkerObstaclePlanStatus.BlockedByLargeObstacle && clearance is null,
    "A small obstacle should remain untouched if clearing it cannot reach the job past a large obstacle.");

WorkerObstacleRoutePlanner hard = new(start, new[] { goal }, point => Corridor(point, WorkerRouteTileKind.Impassable));
status = Run(hard, out clearance);
Assert(status == WorkerObstaclePlanStatus.NoRoute && clearance is null,
    "Map walls and protected player objects must not be described as large removable obstacles.");

WorkerObstacleRoutePlanner detour = new(start, new[] { goal }, point =>
    point.X < 0 || point.X > 4 || point.Y < 1 || point.Y > 2
        ? WorkerRouteTileKind.Impassable
        : point == new Point(2, 1) ? WorkerRouteTileKind.SmallDebris : WorkerRouteTileKind.Open);
status = Run(detour, out clearance);
Assert(status == WorkerObstaclePlanStatus.NoRoute && clearance is null,
    "A free detour should not cause unnecessary clearing.");

object existing = new();
object produced = new();
object laterPlayerDrop = new();
HashSet<object> before = new() { existing };
HashSet<object> captured = WorkerDebrisCapture.CaptureNew(before, new[] { existing, produced });
Assert(captured.SetEquals(new[] { produced }), "Capture must include only debris generated by the tool action.");
Assert(WorkerDebrisCapture.BelongsToZone(produced, before, captured, near: false)
    && !WorkerDebrisCapture.BelongsToZone(existing, before, captured, near: true)
    && !WorkerDebrisCapture.BelongsToZone(laterPlayerDrop, before, captured, near: true),
    "Exact capture must preserve older and later player drops on the ground.");

WorkerObstacleReport report = new() { Id = "current", Message = "Big logs blocked my path.", Task = WorkerTaskKind.ChopHardwood, LocationName = "Farm" };
WorkerObstacleReport? reloaded = JsonSerializer.Deserialize<WorkerObstacleReport>(JsonSerializer.Serialize(report));
Assert(reloaded?.Message == report.Message && WorkerObstacleReportPolicy.MatchesAcknowledgment(reloaded, "current"),
    "The report must survive save serialization and acknowledge its matching ID.");
Assert(!WorkerObstacleReportPolicy.MatchesAcknowledgment(reloaded, "stale")
    && !WorkerObstacleReportPolicy.MatchesAcknowledgment(null, "current"),
    "A delayed multiplayer acknowledgment must not erase a newer or missing report.");

Console.WriteLine("Obstacle route checks passed: small clearing, large reporting, protected terrain, exact drops, and report acknowledgment.");

static WorkerObstaclePlanStatus Run(WorkerObstacleRoutePlanner planner, out WorkerObstacleClearance? clearance)
{
    WorkerObstaclePlanStatus status;
    int updates = 0;
    do
    {
        status = planner.Advance(2, 64, out clearance);
        Assert(++updates <= 100, "A bounded obstacle search must finish in a small test grid.");
    } while (status == WorkerObstaclePlanStatus.Searching);
    return status;
}

static void Assert(bool condition, string message)
{
    if (!condition)
        throw new Exception(message);
}
